spring:
  application:
    name: cadastroninja

  config:
    import: optional:application-local.yaml

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
